<div align = "center >
              <h4> Matrix Operations </4>
              </div>

<div align="center">
    <h4>Data Structure:Matrices</h4>
</div>

**Matrix Construction**

In [2]:
# To construct a matrix in R, you can use the matrix() function which takes several arguments.
# matrix data values
# number of rows 
# number of columns 
# fill the matrix by rows?

x <- matrix(data = c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = FALSE)
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [3]:
# Add the vector c(7,8,9) as a new row


x <- rbind(x, c(7,8,9))
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[3,]    7    8    9


You can add to a matrix you've already constructed with the **rbind()** and **cbind()** functions. rbind() takes a sequence of vectors, matrices or data frames as arguments and combines them by rows, while cbind() combines sequences of data objects by columns.

In [4]:
y <- matrix(seq(10,15,1),3,2) #create a new matrix: 3x2
# add the new matrix to x by column
x <- cbind(x,y)
print(x)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5   10   13
[2,]    2    4    6   11   14
[3,]    7    8    9   12   15


**Note:** 

1. the arguments to rbind() should have the same number of columns and the arguments to cbind() should have the same number of rows.

2. Since cbind() and rbind() work on vectors, you can use them to construct matrices from vectors on a row by row, or column by column basis.

In [5]:
z <-  rbind(c(1,2,3), c(4,5,6), c(7,8,9))
print(z)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


You can turn a matrix's rows into columns and columns into rows using the transpose function **t()** Transpose essentially flips a matrix along the main diagonal.

In [6]:
x <- t(x)
print(x)

     [,1] [,2] [,3]
[1,]    1    2    7
[2,]    3    4    8
[3,]    5    6    9
[4,]   10   11   12
[5,]   13   14   15


You can also convert a matrix into a vector using the **as.vector()** function or the **c()** function.

In [7]:
as.vector(x)  # Convert a matrix into a vector by column

# If you want to convert a matrix to vector by row, take the transpose first:
c(t(x))

[1]  1  3  5 10 13  2  4  6 11 14  7  8  9 12 15

[1]  1  2  7  3  4  8  5  6  9 10 11 12 13 14 15

In [24]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8)
x

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

In [25]:
# One can access a single element of a matrix with x[i,j]:
x[3,2]

[1] 7

In [26]:
# In case, the data has to be entered row wise, then a 4 × 2-matrix X can be created with
y = matrix(nrow = 4, ncol = 2, data = 1:8, byrow = T)
y

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6   
[4,] 7    8

In [27]:
ncol(y)
ncol(x)

nrow(x)
nrow(y)

dim(x)
dim(y)

[1] 2

[1] 2

[1] 4

[1] 4

[1] 4 2

[1] 4 2

In [30]:
help(matrix) # To know more about these important objects, we use help() function on"matrix".

In [31]:
# Assigning a specified number to all matrix elements:
x <- matrix(nrow = 4, ncol = 2, data = 5)
x

[,1] [,2]
[1,] 5    5   
[2,] 5    5   
[3,] 5    5   
[4,] 5    5

**Construction of a diagonal matrix, here the identity matrix of a
dimension 2:**

In [33]:
d = diag(1, nrow = 2, ncol = 2 )
d

[,1] [,2]
[1,] 1    0   
[2,] 0    1

In [34]:
d = diag(3, nrow = 3, ncol = 3)
d

[,1] [,2] [,3]
[1,] 3    0    0   
[2,] 0    3    0   
[3,] 0    0    3

In [36]:
d = diag(1:3, nrow = 3, ncol = 3)
d

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

**Transpose of a matrix X: X’**

In [38]:
x = matrix(nrow = 4, ncol = 2, data = 1:8, byrow = T)
x

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6   
[4,] 7    8

In [40]:
xt = t(x)
xt

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [41]:
# Transpose of a matrix X: X’

xtx = t(x)%*% x
xtx

[,1] [,2]
[1,]  84  100 
[2,] 100  120

In [42]:
# Cross product of a Matrix X, X’X, with a crossprod
xtx2 = crossprod(x)
xtx2

[,1] [,2]
[1,]  84  100 
[2,] 100  120

**Note:** Command crossprod()executes the multiplication faster than the conventional method with **t(x)%*%x**

In [45]:
x = matrix(nrow = 5, ncol = 3, byrow = T, data = 1:15)
x

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12  
[5,] 13   14   15

In [49]:
x[3,] # row
x[,3] # column
x[4:5, 2:3] # sub-mat

[1] 7 8 9

[1]  3  6  9 12 15

[,1] [,2]
[1,] 11   12  
[2,] 14   15

**solve()** function finds the inverse of a positive definite matrix

In [53]:
y <- matrix(nrow = 2, ncol = 2, byrow = T, data = c(85,100,100,120))
y

[,1] [,2]
[1,]  85  100 
[2,] 100  120

In [55]:
solve(y)

[,1] [,2]  
[1,]  0.6 -0.500
[2,] -0.5  0.425

**eigen()** function finds the eigen values and eigen vectors of a positive
definite matrix

In [56]:
eigen(y)

eigen() decomposition
$values
[1] 204.0197025   0.9802975

$vectors
          [,1]       [,2]
[1,] 0.6432805 -0.7656306
[2,] 0.7656306  0.6432805


**Matrix Indexing**

In [8]:
x[3,2] # Get the value at row 3 column 2

[1] 6

In [9]:
#Leave the row or column index blank to take the entire row or column.

x[3, ]   # Get row 3

x[ ,2]   # Get column 2

[1] 5 6 9

[1]  2  4  6 11 14

In [10]:
# Get data points in rows 4 and 5 and columns 2 and 3
print(x[4:5, 2:3])

     [,1] [,2]
[1,]   11   12
[2,]   14   15


In [12]:
print(x[c(1,3,5),c(1,3)])# Vector indexing
      
      


     [,1] [,2]
[1,]    1    7
[2,]    5    9
[3,]   13   15


In [13]:
print(x[ -2, -2] ) # Remove row 2 and remove column 2

     [,1] [,2]
[1,]    1    7
[2,]    5    9
[3,]   10   12
[4,]   13   15


In [14]:
# Create a logical matrix identifying even numbers
X_logical <- (x %% 2 == 0)   
print(X_logical)

      [,1]  [,2]  [,3]
[1,] FALSE  TRUE FALSE
[2,] FALSE  TRUE  TRUE
[3,] FALSE  TRUE FALSE
[4,]  TRUE FALSE  TRUE
[5,] FALSE  TRUE FALSE


In [15]:
# Use the logical matrix as an index to get even values in X
x[X_logical]

[1] 10  2  4  6 14  8 12

In [16]:
# Get matrix values contained in a vector
x[x %in% c(2,6,8,9,10,15,100)]

[1] 10  2  6  8  9 15

A matrix can also have named dimensions. You can assign dimension names when creating a matrix by passing a list of two vectors the dimnames argument.

In [1]:
z = matrix(c(1,2,3,4),2,2, dimnames = list(c("r1", "r2"), c("c1","c2")))
print(z)

   c1 c2
r1  1  3
r2  2  4


You can also create or reassign dimnames after creating a matrix.

In [3]:
dimnames(z) <- list(c("first_r", "second_r"), c("first_c", "second_c"))
print(z)

         first_c second_c
first_r        1        3
second_r       2        4


When dimensions are named, you can index the matrix using the dimension names or the normal numeric indexes.

In [5]:
# Get the value at 2,2 with numeric indexing
z[2,2]
# Get the value at 2,2 with named dimensions
z["second_r", "second_c"]

[1] 4

[1] 4

**Matrix Operations**

Matrices in R offer many of the same conveniences as vectors. For instance, you can perform element-wise math operations on matrices of same dimensions by using the standard math symbols.

In [6]:
#Make two new identical matrices
x <- y <- matrix(c(1,2,-1,1,1,2,1,2,3),3,3)
# You can use the dim() function to check matrix dimensions:
print(x)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    2    1    2
[3,]   -1    2    3


In [7]:
dim(x)

[1] 3 3

In [9]:
# Element-wise addition
print(x + y)

     [,1] [,2] [,3]
[1,]    2    2    2
[2,]    4    2    4
[3,]   -2    4    6


In [10]:
# Element-wise multiplication
print(x * y)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    4    1    4
[3,]    1    4    9


In [11]:
# To perform true matrix multiplication use %*% instead of *.
print(x %*% y)

     [,1] [,2] [,3]
[1,]    2    4    6
[2,]    2    7   10
[3,]    0    7   12


In [12]:
# Get elements on the main diagonal of a matrix
diag(x)

[1] 1 1 3

In [13]:
diag(y)

[1] 1 1 3

In [14]:
sum(x)

[1] 12

In [15]:
min(x)

[1] -1

In [16]:
max(x)

[1] 3

In [17]:
mean(x)

[1] 1.333333

In [18]:
rowSums(x)
colSums(x)
rowMeans(x)
colMeans(x)

[1] 3 5 4

[1] 2 4 6

[1] 1.000000 1.666667 1.333333

[1] 0.6666667 1.3333333 2.0000000

**Note:** sum, min max and mean also work on vectors.

Beyond matrices, R also contains an array data structure that stores elements of the same atomic type in an arbitrary number of dimensions. An array is just a vector stored with an extra attribute "dim" that specifies its dimensions. In other words, arrays let you store data in 3 or more dimensions. Create an array with the **array()** function.

In [19]:
a = array(1:8, dim = c(2,2,2)) #create a 2 x 2 x 2 array

dim(a) # check the dimension of the array
print(a)

[1] 2 2 2

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8



**Exercise #1** Create a 3 x 3 matrix from the vector provided below. Store the matrix as V.

In [20]:
v = c(1:9)
v = matrix(v, 3,3)
v

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

**Exercise #2** Use matrix indexing to get the values in each of the four corners of V.

In [21]:
v[c(1,3), c(1,3)]

[,1] [,2]
[1,] 1    7   
[2,] 3    9

**Exercise #3** Find the sum of the values on the diagonal of V.

In [22]:
sum(diag(v))

[1] 15

**Exercise #4** Use rbind() and cbind() to extend V with itself into a 6 x 6 matrix where each 3 x 3 quadrant is equal to V.

In [23]:
rbind(cbind(v,v), cbind(v,v))

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    4    7    1    4    7   
[2,] 2    5    8    2    5    8   
[3,] 3    6    9    3    6    9   
[4,] 1    4    7    1    4    7   
[5,] 2    5    8    2    5    8   
[6,] 3    6    9    3    6    9

Done:) @Mahendra | SCIS, JNU