<div align="center">
    <h4>Data Structures: List </h4>
</div>

In [1]:
# Create a new list containing a vector, text and a matrix
new_list <- list(c(1,2,3), "R is Fun", matrix(seq(1,6,1),2,3))
print(new_list)

[[1]]
[1] 1 2 3

[[2]]
[1] "R is Fun"

[[3]]
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6



In [2]:
# Create the same list but give the objects names
new_list <- list(vector = c(1,2,3), char_string = "R is Fun", my_matrix = matrix(seq(1,6,1),2,3))
new_list

$vector
[1] 1 2 3

$char_string
[1] "R is Fun"

$my_matrix
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

In [3]:
names(new_list) # access names
names(new_list) <- c("obj1", "obj2", "obj3")
names(new_list)

[1] "vector"      "char_string" "my_matrix"

[1] "obj1" "obj2" "obj3"

1. List of biological data: You can create a list to store different types of biological data related to your analysis. Here's an example:

In [6]:
# List containing gene names, sequences, and functions
gene_list <- list(name = c('GeneA', 'GeneB', 'GeneC'),
                 sequence = c('ATCGATCG', 'TGCAGCA','GGGCCCG'),
                 role = c('Transcription factor', 'Enzyme', "Unknown"))
gene_list

$name
[1] "GeneA" "GeneB" "GeneC"

$sequence
[1] "ATCGATCG" "TGCAGCA"  "GGGCCCG" 

$role
[1] "Transcription factor" "Enzyme"               "Unknown"

2. List of results from bioinformatics tools:Many bioinformatics tools in R packages output results as lists. Here's a generic example:

In [7]:
# Differential expression analysis with DESeq2 package
#library(DESeq2)

# Load data (replace with your actual data)
# ...

# Differential expression results
#de_results <- DESeq(dds)

# This will be a list containing various statistics

**List Indexing**

In [8]:
new_list[1:2]       # Take a slice of the first 2 objects

new_list[2]         # Take a slice that contains only the second object

typeof(new_list[2]) # Check the type of the single-object slice

$obj1
[1] 1 2 3

$obj2
[1] "R is Fun"

$obj2
[1] "R is Fun"

[1] "list"

In [9]:
new_list[[2]]          # Access the second list object

typeof(new_list[[2]])  # Check the object's type

[1] "R is Fun"

[1] "character"

In [10]:
new_list[["obj3"]]

new_list$obj3

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [11]:
# Get obj3 from the list and then access row 2 column 2
new_list[["obj3"]][2,2]

[1] 4

In [12]:
length(new_list)    # Return the length of a list
  
str(new_list)       # Get an overview of the list's structure

summary(new_list)   # Get a summary of the list's contents

[1] 3

List of 3
 $ obj1: num [1:3] 1 2 3
 $ obj2: chr "R is Fun"
 $ obj3: num [1:2, 1:3] 1 2 3 4 5 6


     Length Class  Mode     
obj1 3      -none- numeric  
obj2 1      -none- character
obj3 6      -none- numeric  

In [13]:
new_list$obj4 <- "Additional object"

str(new_list)

List of 4
 $ obj1: num [1:3] 1 2 3
 $ obj2: chr "R is Fun"
 $ obj3: num [1:2, 1:3] 1 2 3 4 5 6
 $ obj4: chr "Additional object"


In [14]:
new_list[[5]] <- "this object has no name!"

str(new_list)

List of 5
 $ obj1: num [1:3] 1 2 3
 $ obj2: chr "R is Fun"
 $ obj3: num [1:2, 1:3] 1 2 3 4 5 6
 $ obj4: chr "Additional object"
 $     : chr "this object has no name!"


In [15]:
second_list <- list("combine me", "with new_list")
combined_list <- c(new_list, second_list)

str(combined_list)

List of 7
 $ obj1: num [1:3] 1 2 3
 $ obj2: chr "R is Fun"
 $ obj3: num [1:2, 1:3] 1 2 3 4 5 6
 $ obj4: chr "Additional object"
 $     : chr "this object has no name!"
 $     : chr "combine me"
 $     : chr "with new_list"


In [16]:
combined_list[[7]] <- NULL   # remove item 7

combined_list$obj1 <- NULL   # remove item the with the name obj1

str(combined_list)

List of 5
 $ obj2: chr "R is Fun"
 $ obj3: num [1:2, 1:3] 1 2 3 4 5 6
 $ obj4: chr "Additional object"
 $     : chr "this object has no name!"
 $     : chr "combine me"


**Exercise #1:** Create a list called "my_list" from the 3 vectors provided below.

In [18]:
a <- "My first list"
b <- c("R", "is", "Fun!")
c <- matrix(1:9,3,3)

mylist <- list(a,b,c)

str(mylist)

List of 3
 $ : chr "My first list"
 $ : chr [1:3] "R" "is" "Fun!"
 $ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9


**Exercise #2:** Access the elements in rows 2 and 3 and columns 2 and 3 of the third object in my_list.

In [20]:
mylist[[3]][2:3,2:3]

[,1] [,2]
[1,] 5    8   
[2,] 6    9

**Exercise #3:** Remove the first and third items from my_list.

In [21]:
mylist[c(1,3)] <- NULL
mylist

[[1]]
[1] "R"    "is"   "Fun!"

**Mode:**

| Object | Example | Mode |
|---|---|---|
| Number | 1.234 | numeric |
| Vector of numbers | c(5, 6, 7, 8) | numeric |
| Character string | "India" | character |
| Vector of character strings | c("India", "USA") | character |
| Factor | factor(c("UP", "MP")) | numeric |
| List | list("India", "USA") | list |
| Data frame | data.frame(x = 1:2, y = c("India", "USA")) | list |
| Function | print | function |

In [1]:
mode(1.234)

[1] "numeric"

In [3]:
mode(c(5,6,7,8))

[1] "numeric"

In [4]:
mode("india")

[1] "character"

In [5]:
mode(c("Mahendra", "is", "Pro", "in", "R"))

[1] "character"

In [6]:
mode(c("MP","UP"))

[1] "character"

In [9]:
mode(factor(c("UP","MP")))

[1] "numeric"

In [10]:
mode(list("India","USA"))

[1] "list"

In [11]:
mode(data.frame(x=1:2, y=c("India","USA")))

[1] "list"

In [12]:
mode(print)

[1] "function"

In [20]:
x1 <- matrix(nrow = 2, ncol = 2, data = 1:4, byrow = T)
x2 <- matrix(nrow = 2, ncol = 2, data = 5:8, byrow = T)

x1
x2

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[,1] [,2]
[1,] 5    6   
[2,] 7    8

In [15]:
x1+x2

[,1] [,2]
[1,]  6    8  
[2,] 10   12

In [18]:
x1[2,1] <- "hello"
x1

[,1]  [,2]
[1,] 1     2   
[2,] hello 4

In [21]:
x1

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [22]:
x2

[,1] [,2]
[1,] 5    6   
[2,] 7    8

In [23]:
matlist <- list(x1,x2)
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [24]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [25]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [26]:
z1 <- list(c("Water","Juice", "Lemonade"), rep(1:4, each = 2), matrix(data = 5:8, nrow = 2,ncol = 2, byrow = T))
z1

[[1]]
[1] "Water"    "Juice"    "Lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

Access the elements of a list using the operator **[[ ]]**

In [27]:
z1[[1]]

[1] "Water"    "Juice"    "Lemonade"

In [28]:
z1[[2]]

[1] 1 1 2 2 3 3 4 4

In [29]:
z1[[3]]

[,1] [,2]
[1,] 5    6   
[2,] 7    8

In [30]:
z1[[1]][1]

[1] "Water"

In [31]:
z1[[2]][2]

[1] 1

In [34]:
z1[[3]][3]

[1] 6